### ISSUE TITLE
Connect to Sentry

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#308] opened 2016-08-25 13:59 UTC
We have a sentry server up and running. Just need to add the project and add the proper configurations to Caseflow Certification.

**Comment by KHarshawat** [comment] 2016-09-01 17:35
Marking this as a dupe of https://github.com/department-of-veterans-affairs/caseflow-certification/issues/57. Closing and adding a comment on the other issue.

**Closed** 2016-09-01 17:36 UTC
Labels: contractor-ready, duplicate
