### ISSUE TITLE
Provide a History of cases for which an EP has been created

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#360] opened 2016-10-24 17:28 UTC
Allow employees to keep track of which cases they have worked and when.

**Comment by KHarshawat** [comment] 2016-11-07 02:11
@lakohl is this a dupe of a story we created last sprint? If so could you please mark as such and close?

**Comment by KHarshawat** [comment] 2016-11-07 02:11
@lakohl can you please add appropriate mocks here?

**Comment by KHarshawat** [comment] 2016-11-07 20:32
Dupe of https://github.com/department-of-veterans-affairs/caseflow-certification/issues/386

**Closed by KHarshawat** 2016-11-07 20:32 UTC
Labels: Current Sprint, Sprint 10/21
